#!/bin/bash                                                                            
AIR_PATH=/opt/AIR-SDK/bin/adl 
APPS_PATH=/opt/AIR-apps 
  
# this is all one line 
${AIR_PATH} -nodebug "${APPS_PATH}/$1/META-INF/AIR/application.xml" "${APPS_PATH}/$1" 